spring:
  datasource:
    username: root
    password: 1119Josebermu
    url: jdbc:mysql://localhost:3306/llega
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
project:
  poster: images/

base:
  url: "http://localhost:8080"
